"""subject update

Revision ID: 53278dfb736c
Revises: e7be8382b565
Create Date: 2024-12-18 12:28:28.090624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53278dfb736c'
down_revision = 'e7be8382b565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
