"""Initial migration

Revision ID: e7be8382b565
Revises: 
Create Date: 2024-11-25 11:44:55.652506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7be8382b565'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_email', 'User', ['email'])
    op.create_unique_constraint('uq_user_username', 'User', ['username'])
    
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('class_name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('user_subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('is_teacher', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_email', 'User', type_='unique')
    op.drop_constraint('uq_user_username', 'User', type_='unique')

    
    op.drop_table('user_subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
